// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCARq8gaiFCpQRy6I4GS4DM-KO8w1SNu4',
    appId: '1:764263533315:web:de974856dba2be7c1f7736',
    messagingSenderId: '764263533315',
    projectId: 'ms-excel-sheet',
    authDomain: 'ms-excel-sheet.firebaseapp.com',
    storageBucket: 'ms-excel-sheet.appspot.com',
    measurementId: 'G-76QNZPBP3X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHYcfyqQeRe24CVDSYauwFKhv3R5-afcw',
    appId: '1:764263533315:android:5d8fb0a09938d1501f7736',
    messagingSenderId: '764263533315',
    projectId: 'ms-excel-sheet',
    storageBucket: 'ms-excel-sheet.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDA3iwj_QAQWNApR7DZ5F-dNzxM0Ybvd2c',
    appId: '1:764263533315:ios:9a6c8c80c42775c31f7736',
    messagingSenderId: '764263533315',
    projectId: 'ms-excel-sheet',
    storageBucket: 'ms-excel-sheet.appspot.com',
    iosClientId:
        '764263533315-euiq0tps1ohkmhpa1vsf4h3kk0qqro5u.apps.googleusercontent.com',
    iosBundleId: 'com.example.msSheet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDA3iwj_QAQWNApR7DZ5F-dNzxM0Ybvd2c',
    appId: '1:764263533315:ios:9a6c8c80c42775c31f7736',
    messagingSenderId: '764263533315',
    projectId: 'ms-excel-sheet',
    storageBucket: 'ms-excel-sheet.appspot.com',
    iosClientId:
        '764263533315-euiq0tps1ohkmhpa1vsf4h3kk0qqro5u.apps.googleusercontent.com',
    iosBundleId: 'com.example.msSheet',
  );
}
