import 'dart:ui' show Color;
import 'package:flutter/material.dart';

class ColorsRes {
  static const Color white = Color(0xFFffffff);
  static const Color mainBlue = Color(0xFF287BFF);
  static const Color lightBlue = Color(0xFFE5EFFF);
  static const Color black = Color(0xFF000000);
  static const Color red = Color(0xFFFF5722);
  static const Color redLight = Color(0x0ddd4a48);
  static const Color grey = Color(0x80ffffff);
  static const Color lightGrey = Color(0xff8B95C9);
  static const Color green = Color(0xff2AD181);
  static const Color lightGreen = Color(0xffF6FFFA);
  static const Color lightWeightColor = Color(0xfff7f7f7);

  static const Color backgroundDark = Color(0xff292929);
  static const Color subTitle = Color(0xff585858);
  static const Color lightFont = Color(0xffa5a5a5);
  static const Color textFieldBackground = Color(0xfff9f9f9);
  static const Color darkFontColor = Color(0xff565759);
  static const Color lightFontColor = Color(0xff939495);
  static const Color shadow = Color(0x0f000000);
  static const Color shadowBottomBar = Color(0x1a2c272e);
  static const Color textFieldBorder = Color(0xffacacac);
  static const Color offWhite = Color(0xfff5f5f5);
  static const Color shadowContainer = Color(0x0f2c272e);
  static const Color shadowTextField = Color(0x1a2c272e);
  static const Color lightPink = Color(0xffe5d7d7);
  static const Color borderColor = Color(0xff707070);
  static const Color shadowCard = Color(0x29000000);
  static const Color darkGrey = Color(0xff757575);
  static const Color greyLightColor = Color(0xffededed);
  static const Color backgroundColor = Color(0xfffff9ef);
  static const Color grayColor = Color(0xff939495);
  static const Color orangeColor = Color(0xFFFF5722);
  static const Color backButtonBoxColor = Color(0x80000000);
  static const Color containerShadowColor = Color(0xffffe8b7);
  static const Color lightWhiteColor = Color(0xfffee8c6);
  static const Color grayTabColor = Color(0xffa1a1a1);
  static const Color splashBackgroundColor = Color(0xfff5f2da);
  static const Color blackTransparentColor = Color(0x80000000);
  static const Color shadowColor = Color(0x29000000);
  static const Color blueColor = Color(0xff0DCAF0);
  static const Color profileBackgroundColor = Color(0xfff7f7f7);

  static const Color blackDartColor = Color(0xff292929);
  static const Color greayLightColor = Color(0xff4f4f4f);
  static const Color lightboarderColor = Color(0xfff7f7f7);
  static const Color darkBlackBoarderTextColor = Color(0xff464646);
  static const Color redLightColor = Color(0x0fdd4a48);
  static const Color redColor2 = Color(0xffffebeb);
  static const Color shaderColor = Color(0x00808080);
  static const Color textGreyColor = Color(0xff999999);
  static const Color cardColor = Color(0xffD5D5D5);
  static const Color backgroundColor2 = Color(0x0f4f4f4f);
  static const Color commentBoxBorderColor = Color(0xffd7d7d7);
  static const Color commentBoxColor = Color(0xfff9f9f9);
  static const Color circleBlurColor = Color(0x14ffffff);
  static const Color yellowColor = Color(0xffebac17);
  static const Color yellowBackgroundColor = Color(0x14ebac17);
  static const Color facebookColor = Color(0xff4267b2);
  static const Color orderTrackingCardYellowColor = Color(0xfffdebd0);
  static const Color orderTrackingCardRedColor = Color(0xFFFF5722);
  static const Color orderTrackingCardGreenColor = Color(0xff33bc88);
  static const Color orderTrackingCardBlueColor = Color(0xffe6e6f6);
  static const Color timeLineColor = Color(0xffb6b6b6);
  static const Color orderTrackingCardOrangeColor = Color(0xFFFF5722);
  static const Color orderTrackingCardPeachColor = Color(0xffFFCCBC);
}
